"""add_member_cash_credit_fields

Revision ID: 05f0e3a41f93
Revises: 93aabbb417e4
Create Date: 2025-12-11 20:07:04.104613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f0e3a41f93'
down_revision: Union[str, None] = '93aabbb417e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to avoid issues with existing rows
    op.add_column('users', sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('users', sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=True))

    # Set default value for existing users
    op.execute("UPDATE users SET cash = 0.00 WHERE cash IS NULL")
    op.execute("UPDATE users SET credit = 0.00 WHERE credit IS NULL")

    # Make columns not nullable
    op.alter_column('users', 'cash', nullable=False, server_default='0.00')
    op.alter_column('users', 'credit', nullable=False, server_default='0.00')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit')
    op.drop_column('users', 'cash')
    # ### end Alembic commands ###
