"""Add RD-Agent tables (rdagent_tasks, generated_factors, factor_evaluations)

Revision ID: 0674a88d143f
Revises: 53c4c4bb9288
Create Date: 2025-12-07 00:32:54.641590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0674a88d143f'
down_revision: Union[str, None] = '53c4c4bb9288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdagent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('FACTOR_MINING', 'STRATEGY_OPTIMIZATION', 'MODEL_EXTRACTION', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=True, comment='輸入參數（JSON 格式）'),
    sa.Column('result', sa.JSON(), nullable=True, comment='任務結果（JSON 格式）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='錯誤訊息'),
    sa.Column('llm_calls', sa.Integer(), nullable=True, comment='LLM API 呼叫次數'),
    sa.Column('llm_cost', sa.Float(), nullable=True, comment='LLM 成本（美元）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rdagent_tasks_id'), 'rdagent_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_rdagent_tasks_status'), 'rdagent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_rdagent_tasks_task_type'), 'rdagent_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_rdagent_tasks_user_id'), 'rdagent_tasks', ['user_id'], unique=False)
    op.create_table('generated_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='因子名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='因子描述'),
    sa.Column('formula', sa.Text(), nullable=False, comment='Qlib 表達式公式'),
    sa.Column('code', sa.Text(), nullable=True, comment='Python 實作代碼（可選）'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='因子類別（如：momentum, value, quality）'),
    sa.Column('ic', sa.Float(), nullable=True, comment='Information Coefficient'),
    sa.Column('icir', sa.Float(), nullable=True, comment='IC Information Ratio'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='Sharpe Ratio'),
    sa.Column('annual_return', sa.Float(), nullable=True, comment='年化報酬率'),
    sa.Column('factor_metadata', sa.JSON(), nullable=True, comment='其他元數據'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['rdagent_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_factors_category'), 'generated_factors', ['category'], unique=False)
    op.create_index(op.f('ix_generated_factors_id'), 'generated_factors', ['id'], unique=False)
    op.create_index(op.f('ix_generated_factors_name'), 'generated_factors', ['name'], unique=False)
    op.create_index(op.f('ix_generated_factors_task_id'), 'generated_factors', ['task_id'], unique=False)
    op.create_index(op.f('ix_generated_factors_user_id'), 'generated_factors', ['user_id'], unique=False)
    op.create_table('factor_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.Integer(), nullable=False),
    sa.Column('stock_pool', sa.String(length=255), nullable=True, comment='股票池'),
    sa.Column('start_date', sa.String(length=20), nullable=True, comment='開始日期'),
    sa.Column('end_date', sa.String(length=20), nullable=True, comment='結束日期'),
    sa.Column('ic', sa.Float(), nullable=True, comment='Information Coefficient'),
    sa.Column('icir', sa.Float(), nullable=True, comment='IC Information Ratio'),
    sa.Column('rank_ic', sa.Float(), nullable=True, comment='Rank IC'),
    sa.Column('rank_icir', sa.Float(), nullable=True, comment='Rank ICIR'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='Sharpe Ratio'),
    sa.Column('annual_return', sa.Float(), nullable=True, comment='年化報酬率'),
    sa.Column('max_drawdown', sa.Float(), nullable=True, comment='最大回撤'),
    sa.Column('win_rate', sa.Float(), nullable=True, comment='勝率'),
    sa.Column('detailed_results', sa.JSON(), nullable=True, comment='詳細評估結果（JSON）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['factor_id'], ['generated_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factor_evaluations_factor_id'), 'factor_evaluations', ['factor_id'], unique=False)
    op.create_index(op.f('ix_factor_evaluations_id'), 'factor_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factor_evaluations_id'), table_name='factor_evaluations')
    op.drop_index(op.f('ix_factor_evaluations_factor_id'), table_name='factor_evaluations')
    op.drop_table('factor_evaluations')
    op.drop_index(op.f('ix_generated_factors_user_id'), table_name='generated_factors')
    op.drop_index(op.f('ix_generated_factors_task_id'), table_name='generated_factors')
    op.drop_index(op.f('ix_generated_factors_name'), table_name='generated_factors')
    op.drop_index(op.f('ix_generated_factors_id'), table_name='generated_factors')
    op.drop_index(op.f('ix_generated_factors_category'), table_name='generated_factors')
    op.drop_table('generated_factors')
    op.drop_index(op.f('ix_rdagent_tasks_user_id'), table_name='rdagent_tasks')
    op.drop_index(op.f('ix_rdagent_tasks_task_type'), table_name='rdagent_tasks')
    op.drop_index(op.f('ix_rdagent_tasks_status'), table_name='rdagent_tasks')
    op.drop_index(op.f('ix_rdagent_tasks_id'), table_name='rdagent_tasks')
    op.drop_table('rdagent_tasks')
    # ### end Alembic commands ###
