"""Add last_verification_token to users table

Revision ID: 13c246798d5c
Revises: e0734313cc1b
Create Date: 2025-12-29 05:34:31.525140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c246798d5c'
down_revision: Union[str, None] = 'e0734313cc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_backtests_pending', table_name='backtests', postgresql_where="((status)::text = 'PENDING'::text)")
    op.drop_index('idx_backtests_running', table_name='backtests', postgresql_where="((status)::text = 'RUNNING'::text)")
    op.drop_index('idx_fundamental_stock_indicator_date_desc', table_name='fundamental_data')
    op.drop_index('idx_institutional_date_type', table_name='institutional_investors')
    op.drop_index('idx_institutional_stock_date_desc', table_name='institutional_investors')
    op.drop_constraint('uq_institutional_investors_stock_date_type', 'institutional_investors', type_='unique')
    op.drop_index('idx_minute_stock_timeframe_datetime_desc', table_name='stock_minute_prices')
    op.drop_constraint('stock_minute_prices_stock_id_fkey', 'stock_minute_prices', type_='foreignkey')
    op.create_foreign_key(None, 'stock_minute_prices', 'stocks', ['stock_id'], ['stock_id'])
    op.drop_index('idx_stock_prices_stock_date_desc', table_name='stock_prices')
    op.drop_index('idx_stocks_active_category', table_name='stocks', postgresql_where="((is_active)::text = 'active'::text)")
    op.drop_index('idx_trades_backtest_stock_date_desc', table_name='trades')
    op.add_column('users', sa.Column('last_verification_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_token')
    op.create_index('idx_trades_backtest_stock_date_desc', 'trades', ['backtest_id', 'stock_id', sa.text('date DESC')], unique=False)
    op.create_index('idx_stocks_active_category', 'stocks', ['category', 'market'], unique=False, postgresql_where="((is_active)::text = 'active'::text)")
    op.create_index('idx_stock_prices_stock_date_desc', 'stock_prices', ['stock_id', sa.text('date DESC')], unique=False)
    op.drop_constraint(None, 'stock_minute_prices', type_='foreignkey')
    op.create_foreign_key('stock_minute_prices_stock_id_fkey', 'stock_minute_prices', 'stocks', ['stock_id'], ['stock_id'], ondelete='CASCADE')
    op.create_index('idx_minute_stock_timeframe_datetime_desc', 'stock_minute_prices', ['stock_id', 'timeframe', sa.text('datetime DESC')], unique=False)
    op.create_unique_constraint('uq_institutional_investors_stock_date_type', 'institutional_investors', ['stock_id', 'date', 'investor_type'])
    op.create_index('idx_institutional_stock_date_desc', 'institutional_investors', ['stock_id', sa.text('date DESC')], unique=False)
    op.create_index('idx_institutional_date_type', 'institutional_investors', [sa.text('date DESC'), 'investor_type'], unique=False)
    op.create_index('idx_fundamental_stock_indicator_date_desc', 'fundamental_data', ['stock_id', 'indicator', sa.text('date DESC')], unique=False)
    op.create_index('idx_backtests_running', 'backtests', ['user_id', sa.text('created_at DESC')], unique=False, postgresql_where="((status)::text = 'RUNNING'::text)")
    op.create_index('idx_backtests_pending', 'backtests', ['user_id', sa.text('created_at DESC')], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
    # ### end Alembic commands ###
