"""add_fundamental_data_table

Revision ID: 26c9e76d37e8
Revises: 39969e96e640
Create Date: 2025-12-03 01:38:34.840824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c9e76d37e8'
down_revision: Union[str, None] = '39969e96e640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False, comment='股票代號'),
    sa.Column('indicator', sa.String(length=50), nullable=False, comment='財務指標名稱'),
    sa.Column('date', sa.String(length=20), nullable=False, comment='數據日期 (e.g., 2024-Q1, 2024-Q2)'),
    sa.Column('value', sa.Float(), nullable=True, comment='指標數值'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='創建時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'indicator', 'date', name='uix_stock_indicator_date')
    )
    op.create_index(op.f('ix_fundamental_data_id'), 'fundamental_data', ['id'], unique=False)
    op.create_index(op.f('ix_fundamental_data_indicator'), 'fundamental_data', ['indicator'], unique=False)
    op.create_index(op.f('ix_fundamental_data_stock_id'), 'fundamental_data', ['stock_id'], unique=False)
    op.create_index('ix_indicator_date', 'fundamental_data', ['indicator', 'date'], unique=False)
    op.create_index('ix_stock_indicator', 'fundamental_data', ['stock_id', 'indicator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_indicator', table_name='fundamental_data')
    op.drop_index('ix_indicator_date', table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_stock_id'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_indicator'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_id'), table_name='fundamental_data')
    op.drop_table('fundamental_data')
    # ### end Alembic commands ###
