"""update user strategy relationship

Revision ID: 2bf429ac7e6e
Revises: 17804433608d
Create Date: 2025-12-31 08:15:37.352358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf429ac7e6e'
down_revision: Union[str, None] = '17804433608d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_model_factors_id'), 'model_factors', ['id'], unique=False)
    op.drop_index('ix_model_training_jobs_status', table_name='model_training_jobs')
    op.create_index(op.f('ix_model_training_jobs_id'), 'model_training_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_training_jobs_id'), table_name='model_training_jobs')
    op.create_index('ix_model_training_jobs_status', 'model_training_jobs', ['status'], unique=False)
    op.drop_index(op.f('ix_model_factors_id'), table_name='model_factors')
    # ### end Alembic commands ###
