"""add performance indexes for strategies and backtests

Revision ID: 39969e96e640
Revises: 3d0286303367
Create Date: 2025-12-02 11:49:52.952580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39969e96e640'
down_revision: Union[str, None] = '3d0286303367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension for GIN index on text search
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    op.create_index('idx_backtest_strategy_created', 'backtests', ['strategy_id', 'created_at'], unique=False)
    op.create_index('idx_backtest_symbol', 'backtests', ['symbol'], unique=False)
    op.create_index('idx_backtest_user_created', 'backtests', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_backtest_user_status', 'backtests', ['user_id', 'status'], unique=False)
    op.create_index('idx_strategy_name_gin', 'strategies', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_strategy_user_created', 'strategies', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_strategy_user_status', 'strategies', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_strategy_user_status', table_name='strategies')
    op.drop_index('idx_strategy_user_created', table_name='strategies')
    op.drop_index('idx_strategy_name_gin', table_name='strategies', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_backtest_user_status', table_name='backtests')
    op.drop_index('idx_backtest_user_created', table_name='backtests')
    op.drop_index('idx_backtest_symbol', table_name='backtests')
    op.drop_index('idx_backtest_strategy_created', table_name='backtests')
    # ### end Alembic commands ###
