"""add member_level to users

Revision ID: 3b79ff8a7aa7
Revises: d6529a74611f
Create Date: 2025-12-10 14:49:08.044827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b79ff8a7aa7'
down_revision: Union[str, None] = 'd6529a74611f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 步驟 1: 先添加欄位（允許 NULL）
    op.add_column('users', sa.Column('member_level', sa.Integer(), nullable=True))

    # 步驟 2: 更新所有現有記錄，設定預設值為 0
    op.execute('UPDATE users SET member_level = 0 WHERE member_level IS NULL')

    # 步驟 3: 設定欄位為 NOT NULL
    op.alter_column('users', 'member_level', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_level')
    # ### end Alembic commands ###
