"""add symbol column to backtests table

Revision ID: 3c968b93aa95
Revises: 0aa53eea675e
Create Date: 2025-12-02 02:11:30.038525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c968b93aa95'
down_revision: Union[str, None] = '0aa53eea675e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代碼'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'symbol')
    # ### end Alembic commands ###
