"""add parameters column to backtests table

Revision ID: 3d0286303367
Revises: 3c968b93aa95
Create Date: 2025-12-02 02:13:29.147739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0286303367'
down_revision: Union[str, None] = '3c968b93aa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('parameters', sa.JSON(), nullable=True, comment='策略參數'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'parameters')
    # ### end Alembic commands ###
