"""Add stock, strategy, backtest models

Revision ID: 430c1561c808
Revises: 705ff3e322a0
Create Date: 2025-12-01 08:34:53.803736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430c1561c808'
down_revision: Union[str, None] = '705ff3e322a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名稱'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='產業分類'),
    sa.Column('market', sa.String(length=20), nullable=True, comment='市場別（上市/上櫃/興櫃）'),
    sa.Column('is_active', sa.String(length=10), nullable=False, comment='狀態（active/delisted）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index('idx_stock_category', 'stocks', ['category'], unique=False)
    op.create_index('idx_stock_market', 'stocks', ['market'], unique=False)
    op.create_index('idx_stock_name', 'stocks', ['name'], unique=False)
    op.create_index(op.f('ix_stocks_stock_id'), 'stocks', ['stock_id'], unique=False)
    op.create_table('stock_prices',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False, comment='開盤價'),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False, comment='最高價'),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False, comment='最低價'),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False, comment='收盤價'),
    sa.Column('volume', sa.BigInteger(), nullable=False, comment='成交量'),
    sa.Column('adj_close', sa.Numeric(precision=10, scale=2), nullable=True, comment='調整後收盤價（考慮除權息）'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stock_id', 'date', name='pk_stock_prices')
    )
    op.create_index('idx_stock_prices_date', 'stock_prices', ['date'], unique=False)
    op.create_index('idx_stock_prices_stock_date', 'stock_prices', ['stock_id', 'date'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='策略名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略描述'),
    sa.Column('code', sa.Text(), nullable=False, comment='策略代碼（Python）'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='策略參數'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='strategystatus', native_enum=False, length=20), nullable=False, comment='策略狀態'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_created_at', 'strategies', ['created_at'], unique=False)
    op.create_index('idx_strategy_status', 'strategies', ['status'], unique=False)
    op.create_index('idx_strategy_user_id', 'strategies', ['user_id'], unique=False)
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='回測名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='回測描述'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='回測開始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='回測結束日期'),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=False, comment='初始資金'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus', native_enum=False, length=20), nullable=False, comment='回測狀態'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='錯誤訊息（如果失敗）'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='開始執行時間'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成執行時間'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_created_at', 'backtests', ['created_at'], unique=False)
    op.create_index('idx_backtest_dates', 'backtests', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_backtest_status', 'backtests', ['status'], unique=False)
    op.create_index('idx_backtest_strategy_id', 'backtests', ['strategy_id'], unique=False)
    op.create_index('idx_backtest_user_id', 'backtests', ['user_id'], unique=False)
    op.create_index(op.f('ix_backtests_id'), 'backtests', ['id'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True, comment='總報酬率（%）'),
    sa.Column('annual_return', sa.Numeric(precision=10, scale=4), nullable=True, comment='年化報酬率（%）'),
    sa.Column('final_portfolio_value', sa.Numeric(precision=15, scale=2), nullable=True, comment='最終資產淨值'),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='夏普比率'),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True, comment='最大回撤（%）'),
    sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True, comment='波動率（標準差）'),
    sa.Column('total_trades', sa.Integer(), nullable=True, comment='總交易次數'),
    sa.Column('winning_trades', sa.Integer(), nullable=True, comment='獲利交易次數'),
    sa.Column('losing_trades', sa.Integer(), nullable=True, comment='虧損交易次數'),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='勝率（%）'),
    sa.Column('average_profit', sa.Numeric(precision=15, scale=2), nullable=True, comment='平均獲利'),
    sa.Column('average_loss', sa.Numeric(precision=15, scale=2), nullable=True, comment='平均虧損'),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True, comment='獲利因子（總獲利/總虧損）'),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='索提諾比率'),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='卡瑪比率'),
    sa.Column('information_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='信息比率'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id')
    )
    op.create_index(op.f('ix_backtest_results_id'), 'backtest_results', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='tradeaction', native_enum=False, length=10), nullable=False, comment='交易動作（buy/sell）'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='交易數量（股數）'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='交易價格'),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False, comment='手續費'),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False, comment='交易稅'),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='交易總額'),
    sa.Column('profit_loss', sa.Numeric(precision=15, scale=2), nullable=True, comment='獲利/虧損（僅 sell 時計算）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_backtest_date', 'trades', ['backtest_id', 'date'], unique=False)
    op.create_index('idx_trade_backtest_id', 'trades', ['backtest_id'], unique=False)
    op.create_index('idx_trade_date', 'trades', ['date'], unique=False)
    op.create_index('idx_trade_stock_id', 'trades', ['stock_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('idx_trade_stock_id', table_name='trades')
    op.drop_index('idx_trade_date', table_name='trades')
    op.drop_index('idx_trade_backtest_id', table_name='trades')
    op.drop_index('idx_trade_backtest_date', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_backtest_results_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index(op.f('ix_backtests_id'), table_name='backtests')
    op.drop_index('idx_backtest_user_id', table_name='backtests')
    op.drop_index('idx_backtest_strategy_id', table_name='backtests')
    op.drop_index('idx_backtest_status', table_name='backtests')
    op.drop_index('idx_backtest_dates', table_name='backtests')
    op.drop_index('idx_backtest_created_at', table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_index('idx_strategy_user_id', table_name='strategies')
    op.drop_index('idx_strategy_status', table_name='strategies')
    op.drop_index('idx_strategy_created_at', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('idx_stock_prices_stock_date', table_name='stock_prices')
    op.drop_index('idx_stock_prices_date', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_stocks_stock_id'), table_name='stocks')
    op.drop_index('idx_stock_name', table_name='stocks')
    op.drop_index('idx_stock_market', table_name='stocks')
    op.drop_index('idx_stock_category', table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
