"""Add generated_models table for AI model generation

Revision ID: 4b53b67e4e01
Revises: 7798771cce99
Create Date: 2025-12-25 21:56:39.088521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b53b67e4e01'
down_revision: Union[str, None] = '7798771cce99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='模型名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('model_type', sa.String(length=100), nullable=False, comment='模型類型（TimeSeries/Tabular）'),
    sa.Column('formulation', sa.Text(), nullable=True, comment='數學公式'),
    sa.Column('architecture', sa.Text(), nullable=True, comment='架構描述'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='變數定義（JSON）'),
    sa.Column('hyperparameters', sa.JSON(), nullable=True, comment='超參數（JSON）'),
    sa.Column('code', sa.Text(), nullable=True, comment='模型實作代碼'),
    sa.Column('qlib_config', sa.JSON(), nullable=True, comment='Qlib 配置（JSON）'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='Sharpe Ratio'),
    sa.Column('annual_return', sa.Float(), nullable=True, comment='年化報酬率'),
    sa.Column('max_drawdown', sa.Float(), nullable=True, comment='最大回撤'),
    sa.Column('information_ratio', sa.Float(), nullable=True, comment='Information Ratio'),
    sa.Column('iteration', sa.Integer(), nullable=True, comment='迭代次數'),
    sa.Column('model_metadata', sa.JSON(), nullable=True, comment='其他元數據'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['rdagent_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_models_id'), 'generated_models', ['id'], unique=False)
    op.create_index(op.f('ix_generated_models_model_type'), 'generated_models', ['model_type'], unique=False)
    op.create_index(op.f('ix_generated_models_name'), 'generated_models', ['name'], unique=False)
    op.create_index(op.f('ix_generated_models_task_id'), 'generated_models', ['task_id'], unique=False)
    op.create_index(op.f('ix_generated_models_user_id'), 'generated_models', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_models_user_id'), table_name='generated_models')
    op.drop_index(op.f('ix_generated_models_task_id'), table_name='generated_models')
    op.drop_index(op.f('ix_generated_models_name'), table_name='generated_models')
    op.drop_index(op.f('ix_generated_models_model_type'), table_name='generated_models')
    op.drop_index(op.f('ix_generated_models_id'), table_name='generated_models')
    op.drop_table('generated_models')
    # ### end Alembic commands ###
