"""add finmind industry chain and custom category tables

Revision ID: 4f097a9131f3
Revises: 73ff25835cf5
Create Date: 2025-12-03 04:57:47.662178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f097a9131f3'
down_revision: Union[str, None] = '73ff25835cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_name', sa.String(length=100), nullable=False, comment='產業鏈名稱'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='產業鏈描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_chains_chain_name'), 'industry_chains', ['chain_name'], unique=True)
    op.create_index(op.f('ix_industry_chains_id'), 'industry_chains', ['id'], unique=False)
    op.create_table('custom_industry_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='創建者用戶 ID'),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='分類名稱'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='分類描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分類 ID（支援階層結構）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['custom_industry_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_name', name='uix_user_category')
    )
    op.create_index(op.f('ix_custom_industry_categories_category_name'), 'custom_industry_categories', ['category_name'], unique=False)
    op.create_index(op.f('ix_custom_industry_categories_id'), 'custom_industry_categories', ['id'], unique=False)
    op.create_table('stock_industry_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False, comment='股票代號'),
    sa.Column('chain_name', sa.String(length=100), nullable=False, comment='產業鏈名稱'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='是否為主要產業鏈'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chain_name'], ['industry_chains.chain_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'chain_name', name='uix_stock_chain')
    )
    op.create_index(op.f('ix_stock_industry_chains_id'), 'stock_industry_chains', ['id'], unique=False)
    op.create_index(op.f('ix_stock_industry_chains_stock_id'), 'stock_industry_chains', ['stock_id'], unique=False)
    op.create_table('stock_custom_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='自定義分類 ID'),
    sa.Column('stock_id', sa.String(length=10), nullable=False, comment='股票代號'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['custom_industry_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'stock_id', name='uix_category_stock')
    )
    op.create_index(op.f('ix_stock_custom_categories_id'), 'stock_custom_categories', ['id'], unique=False)
    op.create_index(op.f('ix_stock_custom_categories_stock_id'), 'stock_custom_categories', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_custom_categories_stock_id'), table_name='stock_custom_categories')
    op.drop_index(op.f('ix_stock_custom_categories_id'), table_name='stock_custom_categories')
    op.drop_table('stock_custom_categories')
    op.drop_index(op.f('ix_stock_industry_chains_stock_id'), table_name='stock_industry_chains')
    op.drop_index(op.f('ix_stock_industry_chains_id'), table_name='stock_industry_chains')
    op.drop_table('stock_industry_chains')
    op.drop_index(op.f('ix_custom_industry_categories_id'), table_name='custom_industry_categories')
    op.drop_index(op.f('ix_custom_industry_categories_category_name'), table_name='custom_industry_categories')
    op.drop_table('custom_industry_categories')
    op.drop_index(op.f('ix_industry_chains_id'), table_name='industry_chains')
    op.drop_index(op.f('ix_industry_chains_chain_name'), table_name='industry_chains')
    op.drop_table('industry_chains')
    # ### end Alembic commands ###
