"""add engine_type to strategies and backtests

Revision ID: 53c4c4bb9288
Revises: 3f228b8913bf
Create Date: 2025-12-05 20:34:03.565945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c4c4bb9288'
down_revision: Union[str, None] = '3f228b8913bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add engine_type columns with default value for existing rows
    op.add_column('backtests', sa.Column('engine_type', sa.String(length=20), nullable=True, comment='使用的回測引擎：backtrader 或 qlib'))
    op.add_column('strategies', sa.Column('engine_type', sa.String(length=20), nullable=True, comment='回測引擎類型：backtrader 或 qlib'))

    # Set default value 'backtrader' for existing rows
    op.execute("UPDATE backtests SET engine_type = 'backtrader' WHERE engine_type IS NULL")
    op.execute("UPDATE strategies SET engine_type = 'backtrader' WHERE engine_type IS NULL")

    # Now make columns NOT NULL
    op.alter_column('backtests', 'engine_type', nullable=False)
    op.alter_column('strategies', 'engine_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'engine_type')
    op.drop_column('backtests', 'engine_type')
    # ### end Alembic commands ###
