"""add_industry_tables

Revision ID: 73ff25835cf5
Revises: 26c9e76d37e8
Create Date: 2025-12-03 01:58:44.082624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ff25835cf5'
down_revision: Union[str, None] = '26c9e76d37e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create industries table without foreign key first
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='產業代碼'),
    sa.Column('name_zh', sa.String(length=100), nullable=False, comment='中文名稱'),
    sa.Column('name_en', sa.String(length=100), nullable=True, comment='英文名稱'),
    sa.Column('parent_code', sa.String(length=20), nullable=True, comment='父產業代碼'),
    sa.Column('level', sa.Integer(), nullable=True, comment='產業層級 (1=大類, 2=中類, 3=小類)'),
    sa.Column('description', sa.Text(), nullable=True, comment='產業描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Create unique index on code (required for foreign key)
    op.create_index(op.f('ix_industries_code'), 'industries', ['code'], unique=True)
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    # Now add the foreign key constraint
    op.create_foreign_key('fk_industries_parent_code', 'industries', 'industries', ['parent_code'], ['code'])
    op.create_table('industry_metrics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=20), nullable=False, comment='產業代碼'),
    sa.Column('date', sa.Date(), nullable=False, comment='數據日期'),
    sa.Column('metric_name', sa.String(length=50), nullable=False, comment='指標名稱 (如 avg_roe, avg_eps)'),
    sa.Column('value', sa.Numeric(), nullable=True, comment='指標值'),
    sa.Column('stocks_count', sa.Integer(), nullable=True, comment='計算基礎的股票數量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_code'], ['industries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_code', 'date', 'metric_name', name='uix_industry_metric')
    )
    op.create_index(op.f('ix_industry_metrics_cache_id'), 'industry_metrics_cache', ['id'], unique=False)
    op.create_index('ix_industry_metrics_code_date', 'industry_metrics_cache', ['industry_code', 'date'], unique=False)
    op.create_index('ix_industry_metrics_name', 'industry_metrics_cache', ['metric_name'], unique=False)
    op.create_table('stock_industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=10), nullable=False, comment='股票代號'),
    sa.Column('industry_code', sa.String(length=20), nullable=False, comment='產業代碼'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='是否為主要產業'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['industry_code'], ['industries.code'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'industry_code', name='uix_stock_industry')
    )
    op.create_index(op.f('ix_stock_industries_id'), 'stock_industries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_industries_id'), table_name='stock_industries')
    op.drop_table('stock_industries')
    op.drop_index('ix_industry_metrics_name', table_name='industry_metrics_cache')
    op.drop_index('ix_industry_metrics_code_date', table_name='industry_metrics_cache')
    op.drop_index(op.f('ix_industry_metrics_cache_id'), table_name='industry_metrics_cache')
    op.drop_table('industry_metrics_cache')
    # Drop foreign key before dropping indexes and table
    op.drop_constraint('fk_industries_parent_code', 'industries', type_='foreignkey')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_index(op.f('ix_industries_code'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
