"""add_timeframe_to_backtests

Revision ID: 93aabbb417e4
Revises: f8bcf88de252
Create Date: 2025-12-11 12:51:17.497933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93aabbb417e4'
down_revision: Union[str, None] = 'f8bcf88de252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('timeframe', sa.String(length=10), nullable=False, server_default='1day', comment='時間粒度：1min, 5min, 15min, 30min, 60min, 1day'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'timeframe')
    # ### end Alembic commands ###
