"""add_telegram_fields_to_users

Revision ID: a1b2c3d4e5f6
Revises: 05f0e3a41f93
Create Date: 2025-12-12 19:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '05f0e3a41f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add Telegram ID (can be username or numeric ID)
    op.add_column('users', sa.Column('telegram_id', sa.String(255), nullable=True))

    # Add Telegram Channel ID (the specific channel/group ID when joining)
    op.add_column('users', sa.Column('telegram_channel_id', sa.String(255), nullable=True))

    # Add index for efficient lookup by telegram_id
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_column('users', 'telegram_channel_id')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
