"""add_strategy_signals_table

Revision ID: bb640c20f0c7
Revises: 20251215_option
Create Date: 2025-12-16 10:33:33.328589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb640c20f0c7'
down_revision: Union[str, None] = '20251215_option'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False, comment='股票代碼'),
    sa.Column('signal_type', sa.String(length=10), nullable=False, comment='信號類型：BUY 或 SELL'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True, comment='檢測時的價格'),
    sa.Column('reason', sa.Text(), nullable=True, comment='信號產生原因'),
    sa.Column('notified', sa.Boolean(), nullable=False, comment='是否已通知用戶'),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True, comment='通知時間'),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='信號檢測時間'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_dedup', 'strategy_signals', ['strategy_id', 'stock_id', 'signal_type', 'detected_at'], unique=False)
    op.create_index('idx_signal_detected_at', 'strategy_signals', ['detected_at'], unique=False)
    op.create_index('idx_signal_notified', 'strategy_signals', ['notified'], unique=False)
    op.create_index('idx_signal_stock_id', 'strategy_signals', ['stock_id'], unique=False)
    op.create_index('idx_signal_strategy_id', 'strategy_signals', ['strategy_id'], unique=False)
    op.create_index('idx_signal_user_id', 'strategy_signals', ['user_id'], unique=False)
    op.create_index('idx_signal_user_time', 'strategy_signals', ['user_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_id'), 'strategy_signals', ['id'], unique=False)
    op.alter_column('institutional_investors', 'date',
               existing_type=sa.DATE(),
               comment='日期',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'stock_id',
               existing_type=sa.VARCHAR(length=10),
               comment='股票代碼',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'investor_type',
               existing_type=sa.VARCHAR(length=50),
               comment='法人類型 (Foreign_Investor, Investment_Trust, Dealer_self, Dealer_Hedging, Foreign_Dealer_Self)',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'buy_volume',
               existing_type=sa.BIGINT(),
               comment='買進股數',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'sell_volume',
               existing_type=sa.BIGINT(),
               comment='賣出股數',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'net_buy_sell',
               existing_type=sa.BIGINT(),
               comment='買賣超（正數=買超，負數=賣超）',
               existing_nullable=True)
    op.drop_index('idx_institutional_date', table_name='institutional_investors')
    op.drop_index('idx_institutional_date_stock', table_name='institutional_investors')
    op.drop_index('idx_institutional_stock_date', table_name='institutional_investors')
    op.drop_index('idx_institutional_stock_id', table_name='institutional_investors')
    op.drop_index('idx_institutional_type', table_name='institutional_investors')
    op.drop_constraint('uq_institutional_date_stock_type', 'institutional_investors', type_='unique')
    op.create_index(op.f('ix_institutional_investors_date'), 'institutional_investors', ['date'], unique=False)
    op.create_index(op.f('ix_institutional_investors_id'), 'institutional_investors', ['id'], unique=False)
    op.create_index(op.f('ix_institutional_investors_investor_type'), 'institutional_investors', ['investor_type'], unique=False)
    op.create_index(op.f('ix_institutional_investors_stock_id'), 'institutional_investors', ['stock_id'], unique=False)
    op.alter_column('option_contracts', 'settlement_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='結算價格（階段一可 NULL，階段三填充）',
               existing_comment='結算價格',
               existing_nullable=True)
    op.create_index(op.f('ix_option_contracts_contract_id'), 'option_contracts', ['contract_id'], unique=False)
    op.drop_constraint('option_contracts_underlying_id_fkey', 'option_contracts', type_='foreignkey')
    op.create_foreign_key(None, 'option_contracts', 'stocks', ['underlying_id'], ['stock_id'])
    op.alter_column('option_daily_factors', 'calculation_version',
               existing_type=sa.VARCHAR(length=10),
               comment='計算版本（用於回測一致性）',
               existing_comment='計算版本',
               existing_nullable=True)
    op.drop_constraint('option_daily_factors_underlying_id_fkey', 'option_daily_factors', type_='foreignkey')
    op.create_foreign_key(None, 'option_daily_factors', 'stocks', ['underlying_id'], ['stock_id'])
    op.drop_constraint('option_greeks_contract_id_fkey', 'option_greeks', type_='foreignkey')
    op.create_foreign_key(None, 'option_greeks', 'option_contracts', ['contract_id'], ['contract_id'])
    op.drop_constraint('option_minute_prices_contract_id_fkey', 'option_minute_prices', type_='foreignkey')
    op.create_foreign_key(None, 'option_minute_prices', 'option_contracts', ['contract_id'], ['contract_id'])
    op.drop_index('ix_telegram_preferences_user_id', table_name='telegram_notification_preferences')
    op.drop_constraint('uq_telegram_preferences_user_id', 'telegram_notification_preferences', type_='unique')
    op.create_index(op.f('ix_telegram_notification_preferences_id'), 'telegram_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_notification_preferences_user_id'), 'telegram_notification_preferences', ['user_id'], unique=True)
    op.drop_index('ix_telegram_notifications_type', table_name='telegram_notifications')
    op.create_index(op.f('ix_telegram_notifications_id'), 'telegram_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_notifications_notification_type'), 'telegram_notifications', ['notification_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_notifications_notification_type'), table_name='telegram_notifications')
    op.drop_index(op.f('ix_telegram_notifications_id'), table_name='telegram_notifications')
    op.create_index('ix_telegram_notifications_type', 'telegram_notifications', ['notification_type'], unique=False)
    op.drop_index(op.f('ix_telegram_notification_preferences_user_id'), table_name='telegram_notification_preferences')
    op.drop_index(op.f('ix_telegram_notification_preferences_id'), table_name='telegram_notification_preferences')
    op.create_unique_constraint('uq_telegram_preferences_user_id', 'telegram_notification_preferences', ['user_id'])
    op.create_index('ix_telegram_preferences_user_id', 'telegram_notification_preferences', ['user_id'], unique=True)
    op.drop_constraint(None, 'option_minute_prices', type_='foreignkey')
    op.create_foreign_key('option_minute_prices_contract_id_fkey', 'option_minute_prices', 'option_contracts', ['contract_id'], ['contract_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'option_greeks', type_='foreignkey')
    op.create_foreign_key('option_greeks_contract_id_fkey', 'option_greeks', 'option_contracts', ['contract_id'], ['contract_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'option_daily_factors', type_='foreignkey')
    op.create_foreign_key('option_daily_factors_underlying_id_fkey', 'option_daily_factors', 'stocks', ['underlying_id'], ['stock_id'], ondelete='CASCADE')
    op.alter_column('option_daily_factors', 'calculation_version',
               existing_type=sa.VARCHAR(length=10),
               comment='計算版本',
               existing_comment='計算版本（用於回測一致性）',
               existing_nullable=True)
    op.drop_constraint(None, 'option_contracts', type_='foreignkey')
    op.create_foreign_key('option_contracts_underlying_id_fkey', 'option_contracts', 'stocks', ['underlying_id'], ['stock_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_option_contracts_contract_id'), table_name='option_contracts')
    op.alter_column('option_contracts', 'settlement_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='結算價格',
               existing_comment='結算價格（階段一可 NULL，階段三填充）',
               existing_nullable=True)
    op.drop_index(op.f('ix_institutional_investors_stock_id'), table_name='institutional_investors')
    op.drop_index(op.f('ix_institutional_investors_investor_type'), table_name='institutional_investors')
    op.drop_index(op.f('ix_institutional_investors_id'), table_name='institutional_investors')
    op.drop_index(op.f('ix_institutional_investors_date'), table_name='institutional_investors')
    op.create_unique_constraint('uq_institutional_date_stock_type', 'institutional_investors', ['date', 'stock_id', 'investor_type'])
    op.create_index('idx_institutional_type', 'institutional_investors', ['investor_type'], unique=False)
    op.create_index('idx_institutional_stock_id', 'institutional_investors', ['stock_id'], unique=False)
    op.create_index('idx_institutional_stock_date', 'institutional_investors', ['stock_id', 'date'], unique=False)
    op.create_index('idx_institutional_date_stock', 'institutional_investors', ['date', 'stock_id'], unique=False)
    op.create_index('idx_institutional_date', 'institutional_investors', ['date'], unique=False)
    op.alter_column('institutional_investors', 'net_buy_sell',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='買賣超（正數=買超，負數=賣超）',
               existing_nullable=True)
    op.alter_column('institutional_investors', 'sell_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='賣出股數',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'buy_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='買進股數',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'investor_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='法人類型 (Foreign_Investor, Investment_Trust, Dealer_self, Dealer_Hedging, Foreign_Dealer_Self)',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'stock_id',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='股票代碼',
               existing_nullable=False)
    op.alter_column('institutional_investors', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='日期',
               existing_nullable=False)
    op.drop_index(op.f('ix_strategy_signals_id'), table_name='strategy_signals')
    op.drop_index('idx_signal_user_time', table_name='strategy_signals')
    op.drop_index('idx_signal_user_id', table_name='strategy_signals')
    op.drop_index('idx_signal_strategy_id', table_name='strategy_signals')
    op.drop_index('idx_signal_stock_id', table_name='strategy_signals')
    op.drop_index('idx_signal_notified', table_name='strategy_signals')
    op.drop_index('idx_signal_detected_at', table_name='strategy_signals')
    op.drop_index('idx_signal_dedup', table_name='strategy_signals')
    op.drop_table('strategy_signals')
    # ### end Alembic commands ###
