"""add email verification fields to users

Revision ID: d6529a74611f
Revises: 3b90289c6cf0
Create Date: 2025-12-10 10:41:31.215996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6529a74611f'
down_revision: Union[str, None] = '3b90289c6cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stock_prices', 'stocks', ['stock_id'], ['stock_id'], ondelete='CASCADE')

    # Add email_verified column with default False for existing users
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default='false'))
    # Update existing users to have email_verified = True (they registered before this feature)
    op.execute("UPDATE users SET email_verified = TRUE WHERE email_verified IS NULL")
    # Now make the column NOT NULL
    op.alter_column('users', 'email_verified', nullable=False)

    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['verification_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'stock_prices', type_='foreignkey')
    # ### end Alembic commands ###
