"""add stock_minute_prices table with timescaledb

Revision ID: f8bcf88de252
Revises: 3b79ff8a7aa7
Create Date: 2025-12-11 06:45:00.916152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bcf88de252'
down_revision: Union[str, None] = '3b79ff8a7aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_minute_prices',
    sa.Column('stock_id', sa.String(length=10), nullable=False),
    sa.Column('datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=10, scale=2), nullable=True, comment='調整後收盤價'),
    sa.Column('trades_count', sa.Integer(), nullable=True, comment='成交筆數'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'datetime', 'timeframe', name='pk_stock_minute_prices'),
    comment='分鐘級股票價格資料表（支援 TimescaleDB hypertable）'
    )
    op.create_index('idx_stock_minute_prices_datetime', 'stock_minute_prices', ['datetime'], unique=False)
    op.create_index('idx_stock_minute_prices_stock_datetime', 'stock_minute_prices', ['stock_id', 'datetime'], unique=False)
    op.create_index('idx_stock_minute_prices_stock_timeframe_datetime', 'stock_minute_prices', ['stock_id', 'timeframe', 'datetime'], unique=False)
    op.create_index('idx_stock_minute_prices_timeframe', 'stock_minute_prices', ['timeframe'], unique=False)
    # ### end Alembic commands ###

    # TimescaleDB Hypertable Configuration
    # 1. Create hypertable with 1-day chunks (分鐘數據量大，使用較小的 chunk)
    op.execute("""
        SELECT create_hypertable(
            'stock_minute_prices',
            'datetime',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE
        );
    """)

    # 2. Enable compression (7 天後自動壓縮，預期壓縮率 60-75%)
    op.execute("""
        ALTER TABLE stock_minute_prices SET (
            timescaledb.compress,
            timescaledb.compress_orderby = 'datetime DESC',
            timescaledb.compress_segmentby = 'stock_id, timeframe'
        );
    """)

    # 3. Add compression policy (自動壓縮 7 天前的數據)
    op.execute("""
        SELECT add_compression_policy('stock_minute_prices', INTERVAL '7 days');
    """)

    # 4. Add retention policy (保留 6 個月數據，可根據存儲容量調整)
    op.execute("""
        SELECT add_retention_policy('stock_minute_prices', INTERVAL '6 months');
    """)


def downgrade() -> None:
    # Remove TimescaleDB policies before dropping table
    # 1. Remove retention policy
    op.execute("""
        SELECT remove_retention_policy('stock_minute_prices', if_exists => true);
    """)

    # 2. Remove compression policy
    op.execute("""
        SELECT remove_compression_policy('stock_minute_prices', if_exists => true);
    """)

    # Note: Hypertable will be automatically dropped when table is dropped

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_minute_prices_timeframe', table_name='stock_minute_prices')
    op.drop_index('idx_stock_minute_prices_stock_timeframe_datetime', table_name='stock_minute_prices')
    op.drop_index('idx_stock_minute_prices_stock_datetime', table_name='stock_minute_prices')
    op.drop_index('idx_stock_minute_prices_datetime', table_name='stock_minute_prices')
    op.drop_table('stock_minute_prices')
    # ### end Alembic commands ###
